### ISSUE TITLE
[FEATURE] Support for Const-me/Whisper with GPU support

### ISSUE THREAD

**Issue by Sharrnah** [mutablelogic/go-whisper#17]
Not sure if it is possible,  but there is a port of the c++ whisper with GPU support.
https://github.com/Const-me/Whisper

It would be nice if this can be used for faster speech to text processing in Golang.

**Comment by djthorpe** [comment]
Just closing out this old issue. These bindings should support CUDA now (in addition to Apple Metal).
You could try again now, if you are using CUDA then use:

```bash
GGML_CUDA=1 make
```

or else just `make` as usual. Please open up a new issue if you're still interested and having some issues.
