### ISSUE TITLE
Have you successfully introduced `whisper` into your project locally?

### ISSUE THREAD

**Issue by guowei-gong** [mutablelogic/go-whisper#19]
When I use `make whisper`, the console always reports the following error.

```
Mkdir build
Mkdir models
Build whisper
sysctl: unknown oid 'hw.optional.arm64'
I whisper.cpp build info:
I UNAME_S:  Darwin
I UNAME_P:  i386
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -DNDEBUG -std=c11   -fPIC -D_DARWIN_C_SOURCE -pthread -mfma -mavx -mavx2 -DGGML_USE_ACCELERATE
I CXXFLAGS: -I. -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -D_DARWIN_C_SOURCE -pthread
I LDFLAGS:   -framework Accelerate
I CC:       Apple clang version 14.0.0 (clang-1400.0.29.202)
I CXX:      Apple clang version 14.0.0 (clang-1400.0.29.202)

make[1]: `libwhisper.a' is up to date.
```
I have seen the same query raised by someone. [issue#597](https://github.com/ggerganov/whisper.cpp/issues/597).

I also tried removing `CFLAGS += -mf16c`. This did not work for me.

Can you please tell me how I should resolve this issue as I want to bind in my own Golang package. It asks me to compile `libwhisper.a`, that is, to run `make whisper` in the `go/buildings` folder.

Could this error be due to the low version of my Mac system? I'm using an Intel Core i7 processor and version 12.6.3.

If so, I'll update my system (it's slow to update and I want to make sure it's not the system version first)

**Comment by guowei-gong** [comment]
When I run `make test` in the `go/buildings` folder, it succeeds!
![image](https://github.com/djthorpe/go-whisper/assets/62499904/1b6734d9-8196-4f60-9391-187f73be81e9)

**Comment by djthorpe** [comment]
Just closing out this old issue! I've update the go-whisper repository. It currently no longer depends on the bindings in whisper.cpp as they are horribly out-of-date (I'll update those later....). If you are still interested and are having issues with this repo, please open a new issue, thank you.
