### ISSUE TITLE
Chromaprint dependency on mac might not be necessary

### ISSUE THREAD

**Issue by RamiAwar** [mutablelogic/go-whisper#46]
Hello!

Thanks for updating the docs, just tried it out and it works!

I uninstalled ffmpeg@7 which I had, then installed @6. 
But when I installed chromaprint after, it re-installed ffmpeg@7. I tried just brew uninstalling chromaprint + ffmpeg@7 and everything worked perfectly then.

Maybe worth checking out.

**Comment by djthorpe** [comment]
Sorry yes, that was my mistake copying it over from another repo. I've now fixed it, thank you.
